rua/apps/common/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, url
from django.views.generic.base import RedirectView, TemplateView

urlpatterns = patterns('common.views',
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about_view'),
    url(r'^license/$', 'license_view', (), 'license_view'),
    url(r'^password/change/done/$', 'password_change_done', (), name='password_change_done'),
    url(r'^object/multiple/action/$', 'multi_object_action_view', (), name='multi_object_action_view'),

    url(r'^user/$', 'current_user_details', (), 'current_user_details'),
    url(r'^user/edit/$', 'current_user_edit', (), 'current_user_edit'),

    url(r'^login/$', 'login_view', (), name='login_view'),
    url(r'^password/change/$', 'password_change_view', (), name='password_change_view'),
)

urlpatterns += patterns('',
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout_view'),

    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset', {'email_template_name': 'password_reset_email.html', 'template_name': 'password_reset_form.html', 'post_reset_redirect': '/password/reset/done'}, name='password_reset_view'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name': 'password_reset_confirm.html', 'post_reset_redirect': '/password/reset/complete/'}, name='password_reset_confirm_view'),
    url(r'^password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'password_reset_complete.html'}, name='password_reset_complete_view'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'password_reset_done.html'}, name='password_reset_done_view'),

    (r'^favicon\.ico$', RedirectView.as_view(url=('%s%s' % (settings.STATIC_URL, 'images/favicon.ico')))),
)

urlpatterns += patterns('',
    url(r'^set_language/$', 'django.views.i18n.set_language', name='set_language'),
)

rua/apps/main/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'home', (), name='home'),
)

rua/apps/permissions/urls.py
from django.conf.urls.defaults import patterns, url
from django.utils.translation import ugettext_lazy as _

from common.views import MayanCreateView, MayanDeleteView, MayanListView, MayanUpdateView

from .models import Role
from .permissions import PERMISSION_ROLE_CREATE, PERMISSION_ROLE_EDIT, PERMISSION_ROLE_VIEW


urlpatterns = patterns('permissions.views',
    url(r'^role/list/$', MayanListView.as_view(queryset=Role.objects.all(), title=_('roles'), global_permissions=[PERMISSION_ROLE_VIEW]), name='role_list'),
    url(r'^role/create/$', MayanCreateView.as_view(model=Role, global_permissions=[PERMISSION_ROLE_CREATE]), name='role_create'),
    url(r'^role/(?P<role_id>\d+)/permissions/$', 'role_permissions', (), name='role_permissions'),
    url(r'^role/(?P<role_id>\d+)/edit/$', 'role_edit', (), name='role_edit'),
    url(r'^role/(?P<role_id>\d+)/delete/$', 'role_delete', (), name='role_delete'),
    url(r'^role/(?P<role_id>\d+)/members/$', 'role_members', (), name='role_members'),

    url(r'^permissions/multiple/grant/$', 'permission_grant', (), name='permission_multiple_grant'),
    url(r'^permissions/multiple/revoke/$', 'permission_revoke', (), name='permission_multiple_revoke'),
)

rua/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls')),
    url(r'^permissions/', include('permissions.urls')),
    url(r'^setup/', include('project_setup.urls')),
    url(r'^tools/', include('project_tools.urls')),
    url(r'^settings/', include('smart_settings.urls')),
    url(r'^user_management/', include('user_management.urls')),
    url(r'^agencies/', include('agencies.urls')),
    url(r'^acls/', include('acls.urls')),
    url(r'^common/', include('common.urls')),
    url(r'^', include('main.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

rua/apps/common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.models import User

SINGLETON_LOCK_ID = 1


class SingletonManager(models.Manager):
    def get(self, **kwargs):
        instance, created = self.model.objects.get_or_create(lock_id=SINGLETON_LOCK_ID, **kwargs)
        return instance


class Singleton(models.Model):
    lock_id = models.CharField(max_length=1, default=SINGLETON_LOCK_ID, editable=False, verbose_name=_(u'lock field'), unique=True)

    objects = SingletonManager()

    def save(self, *args, **kwargs):
        self.id = 1
        super(Singleton, self).save(*args, **kwargs)

    def delete(self, force=False, *args, **kwargs):
        if force:
            return super(Singleton, self).delete(*args, **kwargs)

    class Meta:
        abstract = True


class AnonymousUserSingletonManager(SingletonManager):
    def passthru_check(self, user):
        if isinstance(user, AnonymousUser):
            return self.model.objects.get()
        else:
            return user


class AnonymousUserSingleton(Singleton):
    objects = AnonymousUserSingletonManager()

    def __unicode__(self):
        return ugettext('Anonymous user')

    class Meta:
        verbose_name = _(u'anonymous user')
        verbose_name_plural = _(u'anonymous user')


class AutoAdminSingleton(Singleton):
    account = models.ForeignKey(User, null=True, blank=True, related_name='auto_admin_account', verbose_name=_(u'account'))
    password = models.CharField(null=True, blank=True, verbose_name=_(u'password'), max_length=128)
    password_hash = models.CharField(null=True, blank=True, verbose_name=_(u'password hash'), max_length=128)

    class Meta:
        verbose_name = verbose_name_plural = _(u'auto admin properties')


class LocMemPropertiesMixin(models.Model):
    """
    A mixin model that gives models a list of pseudo fields or properties that
    persists on instantiation of objects from said models
    Example:
    
    Part(LocMemPropertiesMixin, models.Model):
        local_memory_properties = ['label']
        
        part_num = CharField...
        
    hard_disk = Part.objects.create(part_num='hd_1') <= pk == 1
    hard_disk.label = _(u'Hard disk')  <= this property gets stored in ram and related to instance Part, pk == 1
    hard_disk.color = 'blue' <= only assigned to this instance
    
    hd1 = Part.objects.get(pk=1)
    unicode(hd1.label)
    >>> u'Hard disk'
    hd1.color
    >>> AttributeError
    
    Purpose to 'store' in a semi persistent manner properties that have are only
    useful at runtime and not possible or useful to store in a database backend
    such as ugettext values, lambdas, etc
    """

    _properties_registry = {}
    
    def __getattr__(self, attr):
        if attr in self.__class__.local_memory_properties:
            try:
                return self.__class__._properties_registry[self.pk][attr]
            except KeyError:
                return u''
        else:
            raise AttributeError('\'%s\' object has no attribute \'%s\'' % (self.__class__, attr))

    def __setattr__(self, attr, value):
        if attr in self.__class__.local_memory_properties:
            self.__class__._properties_registry.setdefault(self.pk, {})
            self.__class__._properties_registry[self.pk][attr] = value
        else:
            return super(LocMemPropertiesMixin, self).__setattr__(attr, value)

    def __init__(self, *args, **kwargs):
        super(LocMemPropertiesMixin, self).__init__(*args, **kwargs)
        self.__class__._properties_registry.setdefault(self.pk, {})

    class Meta:
        abstract = True

rua/apps/common/forms.py
from __future__ import absolute_import

import os

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.conf import settings

from .utils import return_attrib
from .widgets import (DetailSelectMultiple, PlainWidget, TextAreaDiv,
    EmailInput)


class DetailForm(forms.ModelForm):
    def __init__(self, extra_fields=None, *args, **kwargs):
        super(DetailForm, self).__init__(*args, **kwargs)
        if extra_fields:
            for extra_field in extra_fields:
                result = return_attrib(self.instance, extra_field['field'])
                label = 'label' in extra_field and extra_field['label'] or None
                #TODO: Add others result types <=> Field types
                if isinstance(result, models.query.QuerySet):
                    self.fields[extra_field['field']] = \
                        forms.ModelMultipleChoiceField(
                            queryset=result, label=label)
                else:
                    self.fields[extra_field['field']] = forms.CharField(
                        label=extra_field['label'],
                        initial=return_attrib(self.instance,
                            extra_field['field'], None),
                            widget=PlainWidget)

        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.SelectMultiple):
                self.fields[field_name].widget = DetailSelectMultiple(
                    choices=field.widget.choices,
                    attrs=field.widget.attrs,
                    queryset=getattr(field, 'queryset', None),
                )
                self.fields[field_name].help_text = ''
            elif isinstance(field.widget, forms.widgets.Select):
                self.fields[field_name].widget = DetailSelectMultiple(
                    choices=field.widget.choices,
                    attrs=field.widget.attrs,
                    queryset=getattr(field, 'queryset', None),
                )
                self.fields[field_name].help_text = ''

        for field_name, field in self.fields.items():
            self.fields[field_name].widget.attrs.update({'readonly': 'readonly'})


class GenericConfirmForm(forms.Form):
    def __init__(self, *args, **kwargs):
        pass


class GenericAssignRemoveForm(forms.Form):
    def __init__(self, *args, **kwargs):
        left_list_qryset = kwargs.pop('left_list_qryset', None)
        right_list_qryset = kwargs.pop('right_list_qryset', None)
        left_filter = kwargs.pop('left_filter', None)
        super(GenericAssignRemoveForm, self).__init__(*args, **kwargs)
        if left_filter:
            self.fields['left_list'].queryset = left_list_qryset.filter(
                *left_filter)
        else:
            self.fields['left_list'].queryset = left_list_qryset

        self.fields['right_list'].queryset = right_list_qryset

    left_list = forms.ModelMultipleChoiceField(required=False, queryset=None)
    right_list = forms.ModelMultipleChoiceField(required=False, queryset=None)


class FilterForm(forms.Form):
    def __init__(self, list_filters, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        for list_filter in list_filters:
            label = list_filter.get('title', list_filter['name'])
            self.fields[list_filter['name']] = forms.ModelChoiceField(
                queryset=list_filter['queryset'],
                label=label[0].upper() + label[1:], required=False)


class ChoiceForm(forms.Form):
    """
    Form to be used in side by side templates used to add or remove
    items from a many to many field
    """
    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices', [])
        label = kwargs.pop('label', _(u'Selection'))
        super(ChoiceForm, self).__init__(*args, **kwargs)
        self.fields['selection'].choices = choices
        self.fields['selection'].label = label
        self.fields['selection'].widget.attrs.update({'size': 14, 'class': 'choice_form'})

    selection = forms.MultipleChoiceField()


class UserForm_view(DetailForm):
    """
    Form used to display an user's public details
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'is_staff', 'is_superuser', 'last_login', 'date_joined', 'groups')


class UserForm(forms.ModelForm):
    """
    Form used to edit an user's mininal fields by the user himself
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class EmailAuthenticationForm(AuthenticationForm):
    """
    Override the default authentication form to use email address
    authentication
    """
    email = forms.CharField(label=_(u'Email'), max_length=75,
        widget=EmailInput(attrs={'style': 'width: 100%;'})
    )

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(_('Please enter a correct email and password. Note that the password fields is case-sensitive.'))
            elif not self.user_cache.is_active:
                raise forms.ValidationError(_('This account is inactive.'))
        self.check_for_test_cookie()
        return self.cleaned_data

# Remove the inherited username field
EmailAuthenticationForm.base_fields.keyOrder = ['email', 'password']


class FileDisplayForm(forms.Form):
    text = forms.CharField(
        label='',  # _(u'Text'),
        widget=forms.widgets.Textarea(
            attrs={'cols': 40, 'rows': 20, 'readonly': 'readonly'}
        )
    )

    def __init__(self, *args, **kwargs):
        super(FileDisplayForm, self).__init__(*args, **kwargs)
        changelog_path = os.path.join(settings.PROJECT_ROOT, os.sep.join(self.DIRECTORY), self.FILENAME)
        fd = open(changelog_path)
        self.fields['text'].initial = fd.read()
        fd.close()


class LicenseForm(FileDisplayForm):
    FILENAME = u'LICENSE'
    DIRECTORY = [u'docs', u'credits']

rua/apps/common/templates/generic_assign_remove.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} :: {% blocktrans %}Assign {{ title }} {{ object }}{% endblocktrans %}{% endblock %}


{% block content %}
    <style>
        #id_right_list,#id_left_list { min-width: 28em; min-height: 13em; }
    </style>
    <div class="content">   
    <h2 class="title">{{ title|safe }}</h2>
    
    <form method='POST' action='' id='assign_remove'>{% csrf_token %}
        <input name='action' value='' type='hidden' />
         <table>
            <tbody>
                <tr>
                    <th style='text-align:center;'>{{ left_list_title }}</th><td></td><th style='text-align:center;'>{{ right_list_title }}</th>
                </tr>
                <tr>
                    <td>
                        {{ form.left_list }}{{ form.left_list.errors }}
                    </td>
                    <td>
                        <table>
                            <tbody>
                                <tr>
                                  <td><button class="button" onclick='document.forms["assign_remove"].action.value="assign";document.forms["assign_remove"].submit();'>&gt;</button></td>
                                </tr>
                                <tr>
                                  <td><button class="button" onclick='document.forms["assign_remove"].action.value="remove";document.forms["assign_remove"].submit();'>&lt;</button></td>
                                </tr>
                            </tbody>					
                        </table>
                    </td>
                    <td>{{ form.right_list }}{{ form.right_list.errors }}</td>
                </tr>
                {{ form.media|safe }}			
            </tbody>
        </table>
    </form>
    </div>
{% endblock %}

rua/apps/common/templates/generic_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load common_default_icons_tags %}
{% block title %} :: {% trans "Confirm" %} {{ title }}{% endblock %}

{% block sidebar %}
    {% for subtemplate in subtemplates %}
        {% include subtemplate %}
    {% endfor %}
{% endblock %}

{% block content %}
    {% default_icons %}
    <div class="content">    
        <h2 class="title">
            {% if delete_view %}      
                {% trans "Confirm delete" %}
            {% else %}
                {% trans "Confirm" %}
            {% endif %}
        </h2>
        <div class="inner">
            <form action="" method="post" class="form login">{% csrf_token %}
                {% if next %}
                    <input name="next" type="hidden" value="{{ next }}" />
                {% endif %}   
                       
                {% if previous %}
                    <input name="previous" type="hidden" value="{{ previous }}" />
                {% endif %}   
                
                <div style="float: left; margin-right: 10px;">
                    {% if form_icon %}
                        {{ form_icon.display_big }}
                    {% else %}
                        {{ icon_generic_confirm_icon.display_big }}
                    {% endif %}
                    {#<img style="margin-top: 12px;" src="{{ STATIC_URL }}images/icons/{{ form_icon|default:'question.png' }}" alt="{% trans 'form icon' %}" />#}
                </div>                
                <div style="float: left; width: 90%;">
                {% if title %}
                    <h3>{{ title }}</h3>
                {% else %}
                    {% if delete_view %}
                        {% if object_name %}
                            <h3>{% blocktrans %}Are you sure you wish to delete {{ object_name }}: {{ object }}?{% endblocktrans %}</h3>
                        {% else %}
                            <h3>{% blocktrans %}Are you sure you wish to delete: {{ object }}?{% endblocktrans %}</h3>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <h4>{{ message }}</h4>

                <div class="group navform wat-cf">        
                  <button class="button" type="submit">
                    <img src="{{ STATIC_URL }}web_theme_media/images/icons/tick.png" alt="{% trans 'Yes' %}" /> {% trans "Yes" %}
                  </button>
                  {% if previous %}
                  <a href="#header" onclick='{% if previous %}window.location.replace("{{ previous }}");{% else %}history.go(-1);{% endif %}' class="button">
                    <img src="{{ STATIC_URL }}web_theme_media/images/icons/cross.png"  alt="{% trans 'No' %}"/> {% trans "No" %}
                  </a>
                  {% endif %}
                </div>

                </div>                
                <div class="clear"></div>                 

            </form>
        </div>
    </div>
{% endblock %}

rua/apps/common/templates/generic_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load subtemplates_tags %}

{% block title %} :: {% with "true" as read_only %}{% with "true" as striptags %}{% include "calculate_form_title.html" %}{% endwith %}{% endwith %}{% endblock %}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates %}
        <div class="generic_subform">
            {% include subtemplate %}
        </div>        
    {% endfor %}
  
    {% for subtemplate in sidebar_subtemplates_list %}
        {% with "true" as side_bar %}
            {% if subtemplate.form %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                {% with "true" as read_only %}
                    <div class="generic_subform">
                        {{ rendered_subtemplate }}
                    </div>
                {% endwith %}
            {% else %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                {{ rendered_subtemplate }}
            {% endif %}
                </div>
                {% if subtemplate.grid_clear or not subtemplate.grid %}
                    <div class=""></div> 
            {% endif %}
        {% endwith %}
    {% endfor %}     
{% endblock %}

{% block stylesheets %}
    <style type="text/css">
        #subform form  textarea, 
        #subform form  select option,
        #subform form  input, 
        #subform form  select, 
        #subform form  input { background: none; color: black; border: none; }
    </style>
{% endblock %}

{% block content %}
    {% if form %}
        {% with "true" as read_only %}
            <div class="">
                <div class="generic_subform">
                    {% include "generic_form_subtemplate.html" %}
                </div>
            </div>
            {% if grid_clear or not grid %}
                <div class=""></div> 
            {% endif %}
        {% endwith %}
    {% endif %}
    
    <div class="container_12">
        {% for subtemplate in subtemplates_list %}
            <div class="grid_{{ subtemplate.grid|default:12 }}">       
                {% with "true" as read_only %}
                    {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                    <div class="generic_subform">
                        {{ rendered_subtemplate }}
                    </div>
                {% endwith %}
            </div>
            {% if subtemplate.grid_clear or not subtemplate.grid %}
                <div class="clear"></div> 
            {% endif %}
         {% endfor %}
    </div>    
    
{% endblock %}

rua/apps/common/templates/generic_form.html
{% extends "base.html" %}
{% load subtemplates_tags %}

{% block title %} :: {% with "true" as striptags %}{% include "calculate_form_title.html" %}{% endwith %}{% endblock %}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates_list %}
        {% if subtemplate.form %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                <div class="generic_subform">
                    {{ rendered_subtemplate }}
                </div>
        {% else %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
            {{ rendered_subtemplate }}
        {% endif %}
            {% if subtemplate.grid_clear or not subtemplate.grid %}
            {% endif %}
    {% endfor %}
{% endblock %}

{% block content %}
    {% if form %}
        <div class="generic_subform">
            {% include "generic_form_subtemplate.html" %}
        </div>
    {% endif %}
                             
<div class="container_12">
    {% for subtemplate in subtemplates_list %}
        <div class="grid_{{ subtemplate.grid|default:12 }}">       
            {% if subtemplate.form %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                    <div class="generic_subform">
                        {{ rendered_subtemplate }}
                    </div>
            {% else %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                {{ rendered_subtemplate }}
            {% endif %}
        </div>
        {% if subtemplate.grid_clear or not subtemplate.grid %}
            <div class="clear"></div> 
        {% endif %}
     {% endfor %}
</div>
{% endblock %}

rua/apps/common/templates/generic_form_instance.html
{% load i18n %}
{% load styling %}
{{ form.media|safe }}  
{% add_classes_to_form form %}

{% if form.non_field_errors %}
    <div class="flash">
        {% for value in form.non_field_errors %}
            <div class="message error">
                <p>{{ value }}</p>
            </div>
      {% endfor %}                    
  </div>
{% endif %}

{% if form_display_mode_table %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    <tr class="{% cycle 'odd' 'even2' %}">
    {% for field in form.visible_fields %}
            <td title="{% if field.errors %}{% for error in field.errors %}{{ error }}{% if not forloop.last %} | {% endif %}{% endfor %}{% else %}{{ field.help_text }}{% endif %}">
            {% if field.errors %}<div class="flash"><div class="error">{% endif %}
              {{ field }}
            {% if field.errors %}</div></div>{% endif %}
            </td>
    {% endfor %} 
    </tr>
{% else %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    
    {% for field in form.visible_fields %}
        <div class="group">
            {% if field.errors %}<div class="fieldWithErrors">{% endif %}
            <label class="label">{{ field.label_tag }}{% if field.field.required and not read_only and not form_hide_required_text %} ({% trans "required" %}){% endif %}</label>
            {% if field.errors %}<span class="error">{% for error in field.errors %}{{ error }}{% if not forloop.last %} | {% endif %}{% endfor %}</span></div>{% endif %} 
            {{ field }}
            {% if field.help_text %}<span class="description">{{ field.help_text }}</span>{% endif %}
        </div>
    {% endfor %} 
{% endif %}

rua/apps/common/templates/generic_form_subtemplate.html
{% load i18n %}
{% load common_default_icons_tags %}
{% default_icons %}
  
{% if side_bar %}
    <div class="block">
    <h3>
{% else %}
    <div class="content">    
    <h2 class="title">
{% endif %}

{% include "calculate_form_title.html" %}

{% if side_bar %}
    </h3>
    <div class="content">
        <p>
{% else %}
    </h2>
    <div class="inner">
{% endif %}
    {% if form.is_multipart %}
        <form name="{{ form.prefix }}" enctype="multipart/form-data" method="{{ submit_method|default:'post' }}" action="{{ form_action }}" class="form">
    {% else %}
        <form name="{{ form.prefix }}" method="{{ submit_method|default:'post' }}" action="{{ form_action }}" class="form">
    {% endif %}
        {% if step_field %}
            <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
        {% endif %}
        
        {% if submit_method != "GET" and submit_method != "get" %}
            {% csrf_token %}
        {% endif %}
        
        {% if next %}
            <input name="next" type="hidden" value="{{ next }}" />
        {% endif %}          

        {% if previous %}
            <input name="previous" type="hidden" value="{{ previous }}" />
        {% endif %}

        {% for hidden_field in hidden_fields %}
           {{ hidden_field.as_hidden }}
        {% endfor %}
                   
        {% if form.management_form %}
            {% with form as formset %}
                {{ formset.management_form }}

                {% if form_display_mode_table %}
                    <table class="table">
                        <tbody>
                        <tr>
                            {% for field in formset.forms.0.visible_fields %}
                                <th>
                                    {{ field.label_tag }}{% if field.field.required and not read_only %} ({% trans "required" %}){% endif %}
                                </th>
                            {#{% if field.help_text %}<span class="description">{{ field.help_text }}</span>{% endif %}#}
                            {% endfor %} 
                        </tr>
                {% endif %}
                
                {% for form in formset.forms %}
                    {% include "generic_form_instance.html" %}
                {% endfor %}
                {% if form_display_mode_table %}
                    </tbody>
                    </table>
                {% endif %}
            {% endwith %}
        {% else %}
            {% include "generic_form_instance.html" %}
        {% endif %}
        {% if not read_only %}
        <div class="group navform wat-cf">
            <button class="button" type="submit" name="{% if form.prefix %}{{ form.prefix }}-submit{% else %}submit{% endif %}">
                {% if submit_icon %}
                    {{ submit_icon.display_small }}
                {% else %}
                    {{ icon_submit_default.display_small }}
                {% endif %}
                
                {% if submit_label %}{{ submit_label }}{% else %}{% if object %}{% trans "Save" %}{% else %}{% trans "Submit" %}{% endif %}{% endif %}
            </button>

              {% if previous %}
                  <a href="#header" onclick='{% if previous %}window.location.replace("{{ previous }}");{% else %}history.go(-1);{% endif %}' class="button">
                    {% if cancel_icon %}
                        {{ cancel_icon.display_small }}
                    {% else %}
                        {{ icon_cancel_default.display_small }}
                    {% endif %}
                      
                    {% if cancel_label %}{{ cancel_label }}{% else %}{% trans "Cancel" %}{% endif %}
                  </a>
              {% endif %}
        </div>
        {% endif %}
    </form>
    {% if side_bar %}
        </p></div><!--end content--></div><!--end block-->
    {% else %}
        </div></div>
    {% endif %}

rua/apps/common/templates/generic_list.html
{% extends "base.html" %}
{% load i18n %}
{% load navigation_tags %}
{% load subtemplates_tags %}

{% block title %} :: {% blocktrans with title|striptags as stripped_title %}List of {{ stripped_title }}{% endblocktrans %}{% endblock %}
{#{% block secondary_links %}{{ secondary_links|safe }}{% endblock %}#}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates_list %}
        {% if subtemplate.form %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                <div class="generic_subform">
                    {{ rendered_subtemplate }}
                </div>
        {% else %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
            {{ rendered_subtemplate }}
        {% endif %}
     {% endfor %}

{% endblock %}

{% block content %}
    {% include "generic_list_subtemplate.html" %}
{% endblock %}